services:

  # PostgreSQL database
  postgres:
      container_name: postgres
      image: postgres:15-alpine
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "${POSTGRES_PORT:-5432}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
      env_file:
        - ".env"
      networks:
        - wallet_service_network

  # FastAPI application
  app:
    container_name: app
    build: .
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: ["/entrypoint.sh"]
    networks:
      - wallet_service_network

volumes:
  postgres_data:

networks:
  wallet_service_network:
    driver: bridge